#!/usr/bin/env bash
# =============================================================================
# Doctrine export tests: rules engine stays the source of truth, output is
# regenerable, and rule overrides are reflected in every harness file.
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$SCRIPT_DIR/../lib/test-helpers.sh"

CLI="$ROOT_DIR/ci/craftsman-ci.sh"
WORK="/tmp/craftsman-export-test-$$"
mkdir -p "$WORK"
PREV_PWD="$PWD"
cd "$WORK"

echo "=== Export targets ==="

bash "$CLI" export --target all >/dev/null 2>&1

for file in "AGENTS.md" ".cursor/rules/craftsman.mdc" ".github/copilot-instructions.md"; do
    if [[ -f "$file" ]]; then
        log_pass "generated $file"
    else
        log_fail "export target" "$file missing"
    fi
done

if head -3 AGENTS.md | grep -q "Generated by craftsman-ci export"; then
    log_pass "AGENTS.md block marked as generated"
else
    log_fail "generated marker" "missing generated header"
fi

if head -5 .cursor/rules/craftsman.mdc | grep -q "alwaysApply: true"; then
    log_pass "cursor rule carries alwaysApply frontmatter"
else
    log_fail "cursor frontmatter" "missing alwaysApply"
fi

echo ""
echo "=== Content derives from the rules engine ==="

for rule in PHP001 LAYER001 LAYER004 DB003; do
    if grep -q "\*\*${rule}\*\*" AGENTS.md; then
        log_pass "AGENTS.md documents ${rule}"
    else
        log_fail "rule coverage" "${rule} missing from AGENTS.md"
    fi
done

# An ignored rule must disappear from the generated doctrine
cat > .craft-config.yml <<'YAML'
v: 4
strictness: strict
rules:
  PHP002: ignore
  DB001: warn
YAML

bash "$CLI" export --target agents-md >/dev/null 2>&1

if ! grep -q "\*\*PHP002\*\*" AGENTS.md; then
    log_pass "rule set to ignore is omitted from the doctrine"
else
    log_fail "ignore handling" "PHP002 still present after ignore override"
fi

if grep -q "\*\*DB001\*\* (warn)" AGENTS.md; then
    log_pass "severity override (warn) is reflected in the doctrine"
else
    log_fail "severity override" "DB001 not rendered as warn: $(grep DB001 AGENTS.md || echo missing)"
fi

echo ""
echo "=== The doctrine describes every rule the engine can emit ==="

# Four hardcoded lists used to cover 15 of the 38 rules the validators emit, and
# three of those 15 named the wrong rule: PHP003 was documented as "private
# constructor plus factory" while it enforces "no public setter", PHP004 as "no
# setters" while it enforces "no new DateTime()", TS002 as "readonly by default"
# while it enforces "no default export". A teammate on Codex reads this file and
# is blocked by a rule it never mentioned, or by one it described as something
# else. That is the drift the plugin exists to prevent, in the very artefact
# meant to carry the doctrine outward.
#
# Analyser passthrough codes (PHPSTAN*, ESLINT*, DEPTRAC*) are outside this
# contract: their text is the external tool's, not doctrine.
source "$ROOT_DIR/ci/doctrine-export.sh"
rm -f .craft-config.yml
bash "$CLI" export --target agents-md >/dev/null 2>&1

# -I and --exclude-dir: hooks/lib modules now import each other, so Python
# writes __pycache__ there in normal use. grep reports "Binary file ... matches"
# for a .pyc, that line lands in the rule list, and every downstream assertion
# then compares a filename against the doctrine. The guard was reporting drift
# that did not exist.
ENFORCED=$(grep -rhoIE --exclude-dir=__pycache__ \
    '\b(PHP|TS|LAYER|DB|PY|SH|SEC|GOD|LOC|NEST|PARAM|CTRL|RATCHET|WARN-[A-Z]+)[0-9]{3}\b' \
    "$ROOT_DIR/hooks" "$ROOT_DIR/packs" 2>/dev/null | sort -u)

UNDOCUMENTED=""
UNRENDERED=""
for rule in $ENFORCED; do
    # A rule with no entry falls through to the default branch, which echoes
    # the id straight back.
    [[ "$(_doctrine_rule_text "$rule")" == "$rule" ]] && UNDOCUMENTED="${UNDOCUMENTED} ${rule}"
    grep -q "\*\*${rule}\*\*" AGENTS.md 2>/dev/null || UNRENDERED="${UNRENDERED} ${rule}"
done

if [[ -z "$UNDOCUMENTED" ]]; then
    log_pass "all $(echo "$ENFORCED" | wc -w | tr -d ' ') enforced rules have doctrine text"
else
    log_fail "doctrine drift" "enforced but undocumented:${UNDOCUMENTED}"
fi

if [[ -z "$UNRENDERED" ]]; then
    log_pass "every enforced rule reaches the rendered file"
else
    log_fail "doctrine not rendered" "documented but absent from output:${UNRENDERED}"
fi

# A context file past 20000 characters is truncated by Hermes, 70% head and 20%
# tail, so an overflowing doctrine loses its middle without saying so.
DOCTRINE_SIZE=$(wc -c < AGENTS.md | tr -d ' ')
if [[ "$DOCTRINE_SIZE" -lt 20000 ]]; then
    log_pass "rendered doctrine is ${DOCTRINE_SIZE} chars, inside the 20000 context-file limit"
else
    log_fail "doctrine too large" "${DOCTRINE_SIZE} chars, harnesses truncate past 20000"
fi

echo ""
echo "=== Regeneration is stable ==="

cp AGENTS.md first-run.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if diff -q first-run.md AGENTS.md >/dev/null 2>&1; then
    log_pass "re-export produces identical output (no churn in git)"
else
    log_fail "stability" "output differs between runs"
fi

EXIT_CODE=0
bash "$CLI" export --target nonsense >/dev/null 2>&1 || EXIT_CODE=$?
if [[ $EXIT_CODE -ne 0 ]]; then
    log_pass "unknown target exits non-zero"
else
    log_fail "unknown target" "should fail"
fi

# --- an existing instruction file is the user's; the export owns one block --
#
# The real CLI on a fixture holding a witness instruction returned 0 and
# replaced the whole file: the witness was gone (audit CR-117, C4). The export
# now writes a delimited block, creates the file when absent, appends the block
# to a file that has none, and rewrites only the block when it is there.
echo ""
echo "--- existing AGENTS.md is preserved ---"
cat > AGENTS.md <<'USER'
# Team instructions

- WITNESS: always run `make ci-local` before a PR.

## Deploy

Ask ops before touching the staging bucket.
USER
cp AGENTS.md user-only.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q "WITNESS: always run" AGENTS.md && grep -q "Ask ops before touching" AGENTS.md; then
    log_pass "the user's instructions survive an export"
else
    log_fail "user instructions lost" "$(head -5 AGENTS.md | tr '\n' '|')"
fi
if grep -q '<!-- craftsman:doctrine:begin' AGENTS.md && grep -q '<!-- craftsman:doctrine:end -->' AGENTS.md && grep -q '\*\*LAYER001\*\*' AGENTS.md; then
    log_pass "the doctrine is appended as one delimited block carrying its provenance"
else
    log_fail "delimited block" "$(grep -n 'craftsman:doctrine' AGENTS.md | tr '\n' '|')"
fi
cp AGENTS.md after-one.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if diff -q after-one.md AGENTS.md >/dev/null 2>&1 \
    && [[ "$(grep -c 'craftsman:doctrine:begin' AGENTS.md)" == "1" ]] \
    && [[ "$(grep -c 'WITNESS: always run' AGENTS.md)" == "1" ]]; then
    log_pass "a second export rewrites the block in place: no duplication, no churn"
else
    log_fail "idempotent block" "begin markers=$(grep -c 'craftsman:doctrine:begin' AGENTS.md) witness=$(grep -c 'WITNESS' AGENTS.md)"
fi
# the user's text after the block is kept too, and the block is regenerated
printf '\n## After the doctrine\n\nWITNESS-2: keep me.\n' >> AGENTS.md
sed -i.bak 's/\*\*LAYER001\*\*/**LAYER001-STALE**/' AGENTS.md && rm -f AGENTS.md.bak
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q "WITNESS-2: keep me" AGENTS.md && grep -q '\*\*LAYER001\*\*' AGENTS.md && ! grep -q 'LAYER001-STALE' AGENTS.md; then
    log_pass "text after the block is kept and a hand-edited block is regenerated from the engine"
else
    log_fail "block regeneration" "$(grep -n 'LAYER001\|WITNESS-2' AGENTS.md | tr '\n' '|')"
fi
# the same contract for the Copilot instruction file
mkdir -p .github
printf '# Copilot notes\n\nWITNESS-C: prefer small PRs.\n' > .github/copilot-instructions.md
bash "$CLI" export --target copilot >/dev/null 2>&1
if grep -q "WITNESS-C" .github/copilot-instructions.md && grep -q 'craftsman:doctrine:begin' .github/copilot-instructions.md; then
    log_pass "the Copilot instruction file is treated the same way"
else
    log_fail "copilot preservation" "$(head -3 .github/copilot-instructions.md | tr '\n' '|')"
fi

# Review of 95c431e: an orphan begin marker paired with the end of the block
# the first export appended, and the second export deleted everything between
# them. Malformed markers are refused, never guessed.
printf '# Notes\n\n<!-- craftsman:doctrine:begin version=old -->\nWITNESS-3: orphan begin, keep me.\n' > AGENTS.md
cp AGENTS.md orphan.md
RC=0; bash "$CLI" export --target agents-md >/dev/null 2>/tmp/orphan.err || RC=$?
if [[ "$RC" -ne 0 ]] && diff -q orphan.md AGENTS.md >/dev/null && grep -q "marker" /tmp/orphan.err; then
    log_pass "a begin marker without its end refuses the export and leaves the file untouched"
else
    log_fail "orphan begin" "rc=$RC $(head -3 AGENTS.md | tr '\n' '|') err=$(cat /tmp/orphan.err | head -1)"
fi
printf '<!-- craftsman:doctrine:end -->\n# Notes\n<!-- craftsman:doctrine:begin version=old -->\nWITNESS-4\n<!-- craftsman:doctrine:end -->\n' > AGENTS.md
RC=0; bash "$CLI" export --target agents-md >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 ]] && grep -q "WITNESS-4" AGENTS.md; then
    log_pass "two end markers refuse the export and keep the text"
else
    log_fail "ambiguous markers" "rc=$RC"
fi
# Line endings and mode outside the block are the user's.
printf '# CRLF notes\r\n\r\nWITNESS-5: keep my CRLF.\r\n' > AGENTS.md
chmod 664 AGENTS.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q $'WITNESS-5: keep my CRLF.\r$' AGENTS.md && grep -q $'craftsman:doctrine:end -->\r$' AGENTS.md \
    && [[ "$(stat -f '%Lp' AGENTS.md 2>/dev/null || stat -c '%a' AGENTS.md)" == "664" ]]; then
    log_pass "a CRLF file keeps its line endings (block included) and its mode after the export"
else
    log_fail "CRLF and mode" "mode=$(stat -f '%Lp' AGENTS.md 2>/dev/null || stat -c '%a' AGENTS.md) $(head -c 60 AGENTS.md | od -c | head -2 | tr '\n' ' ')"
fi
rm -f orphan.md
rm -f AGENTS.md user-only.md after-one.md

cd "$PREV_PWD"
rm -rf "$WORK"

test_summary
