#!/usr/bin/env bash
# =============================================================================
# Doctrine export tests: rules engine stays the source of truth, output is
# regenerable, and rule overrides are reflected in every harness file.
# =============================================================================
set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
source "$SCRIPT_DIR/../lib/test-helpers.sh"

CLI="$ROOT_DIR/ci/craftsman-ci.sh"
WORK="/tmp/craftsman-export-test-$$"
mkdir -p "$WORK"
PREV_PWD="$PWD"
cd "$WORK"

echo "=== Export targets ==="

bash "$CLI" export --target all >/dev/null 2>&1

for file in "AGENTS.md" ".cursor/rules/craftsman.mdc" ".github/copilot-instructions.md"; do
    if [[ -f "$file" ]]; then
        log_pass "generated $file"
    else
        log_fail "export target" "$file missing"
    fi
done

if head -3 AGENTS.md | grep -q "Generated by craftsman-ci export"; then
    log_pass "AGENTS.md block marked as generated"
else
    log_fail "generated marker" "missing generated header"
fi

if head -5 .cursor/rules/craftsman.mdc | grep -q "alwaysApply: true"; then
    log_pass "cursor rule carries alwaysApply frontmatter"
else
    log_fail "cursor frontmatter" "missing alwaysApply"
fi

echo ""
echo "=== Content derives from the rules engine ==="

for rule in PHP001 LAYER001 LAYER004 DB003; do
    if grep -q "\*\*${rule}\*\*" AGENTS.md; then
        log_pass "AGENTS.md documents ${rule}"
    else
        log_fail "rule coverage" "${rule} missing from AGENTS.md"
    fi
done

# An ignored rule must disappear from the generated doctrine
cat > .craft-config.yml <<'YAML'
v: 4
strictness: strict
rules:
  PHP002: ignore
  DB001: warn
YAML

bash "$CLI" export --target agents-md >/dev/null 2>&1

if ! grep -q "\*\*PHP002\*\*" AGENTS.md; then
    log_pass "rule set to ignore is omitted from the doctrine"
else
    log_fail "ignore handling" "PHP002 still present after ignore override"
fi

if grep -q "\*\*DB001\*\* (warn)" AGENTS.md; then
    log_pass "severity override (warn) is reflected in the doctrine"
else
    log_fail "severity override" "DB001 not rendered as warn: $(grep DB001 AGENTS.md || echo missing)"
fi

echo ""
echo "=== The doctrine describes every rule the engine can emit ==="

# Four hardcoded lists used to cover 15 of the 38 rules the validators emit, and
# three of those 15 named the wrong rule: PHP003 was documented as "private
# constructor plus factory" while it enforces "no public setter", PHP004 as "no
# setters" while it enforces "no new DateTime()", TS002 as "readonly by default"
# while it enforces "no default export". A teammate on Codex reads this file and
# is blocked by a rule it never mentioned, or by one it described as something
# else. That is the drift the plugin exists to prevent, in the very artefact
# meant to carry the doctrine outward.
#
# Analyser passthrough codes (PHPSTAN*, ESLINT*, DEPTRAC*) are outside this
# contract: their text is the external tool's, not doctrine.
source "$ROOT_DIR/ci/doctrine-export.sh"
rm -f .craft-config.yml
bash "$CLI" export --target agents-md >/dev/null 2>&1

# -I and --exclude-dir: hooks/lib modules now import each other, so Python
# writes __pycache__ there in normal use. grep reports "Binary file ... matches"
# for a .pyc, that line lands in the rule list, and every downstream assertion
# then compares a filename against the doctrine. The guard was reporting drift
# that did not exist.
ENFORCED=$(grep -rhoIE --exclude-dir=__pycache__ \
    '\b(PHP|TS|LAYER|DB|PY|SH|SEC|GOD|LOC|NEST|PARAM|CTRL|RATCHET|WARN-[A-Z]+)[0-9]{3}\b' \
    "$ROOT_DIR/hooks" "$ROOT_DIR/packs" 2>/dev/null | sort -u)

UNDOCUMENTED=""
UNRENDERED=""
for rule in $ENFORCED; do
    # A rule with no entry falls through to the default branch, which echoes
    # the id straight back.
    [[ "$(_doctrine_rule_text "$rule")" == "$rule" ]] && UNDOCUMENTED="${UNDOCUMENTED} ${rule}"
    grep -q "\*\*${rule}\*\*" AGENTS.md 2>/dev/null || UNRENDERED="${UNRENDERED} ${rule}"
done

if [[ -z "$UNDOCUMENTED" ]]; then
    log_pass "all $(echo "$ENFORCED" | wc -w | tr -d ' ') enforced rules have doctrine text"
else
    log_fail "doctrine drift" "enforced but undocumented:${UNDOCUMENTED}"
fi

if [[ -z "$UNRENDERED" ]]; then
    log_pass "every enforced rule reaches the rendered file"
else
    log_fail "doctrine not rendered" "documented but absent from output:${UNRENDERED}"
fi

# A context file past 20000 characters is truncated by Hermes, 70% head and 20%
# tail, so an overflowing doctrine loses its middle without saying so.
DOCTRINE_SIZE=$(wc -c < AGENTS.md | tr -d ' ')
if [[ "$DOCTRINE_SIZE" -lt 20000 ]]; then
    log_pass "rendered doctrine is ${DOCTRINE_SIZE} chars, inside the 20000 context-file limit"
else
    log_fail "doctrine too large" "${DOCTRINE_SIZE} chars, harnesses truncate past 20000"
fi

echo ""
echo "=== Regeneration is stable ==="

cp AGENTS.md first-run.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if diff -q first-run.md AGENTS.md >/dev/null 2>&1; then
    log_pass "re-export produces identical output (no churn in git)"
else
    log_fail "stability" "output differs between runs"
fi

EXIT_CODE=0
bash "$CLI" export --target nonsense >/dev/null 2>&1 || EXIT_CODE=$?
if [[ $EXIT_CODE -ne 0 ]]; then
    log_pass "unknown target exits non-zero"
else
    log_fail "unknown target" "should fail"
fi

# --- an existing instruction file is the user's; the export owns one block --
#
# The real CLI on a fixture holding a witness instruction returned 0 and
# replaced the whole file: the witness was gone (audit CR-117, C4). The export
# now writes a delimited block, creates the file when absent, appends the block
# to a file that has none, and rewrites only the block when it is there.
echo ""
echo "--- existing AGENTS.md is preserved ---"
cat > AGENTS.md <<'USER'
# Team instructions

- WITNESS: always run `make ci-local` before a PR.

## Deploy

Ask ops before touching the staging bucket.
USER
cp AGENTS.md user-only.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q "WITNESS: always run" AGENTS.md && grep -q "Ask ops before touching" AGENTS.md; then
    log_pass "the user's instructions survive an export"
else
    log_fail "user instructions lost" "$(head -5 AGENTS.md | tr '\n' '|')"
fi
if grep -q '<!-- craftsman:doctrine:begin' AGENTS.md && grep -q '<!-- craftsman:doctrine:end -->' AGENTS.md && grep -q '\*\*LAYER001\*\*' AGENTS.md; then
    log_pass "the doctrine is appended as one delimited block carrying its provenance"
else
    log_fail "delimited block" "$(grep -n 'craftsman:doctrine' AGENTS.md | tr '\n' '|')"
fi
cp AGENTS.md after-one.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if diff -q after-one.md AGENTS.md >/dev/null 2>&1 \
    && [[ "$(grep -c 'craftsman:doctrine:begin' AGENTS.md)" == "1" ]] \
    && [[ "$(grep -c 'WITNESS: always run' AGENTS.md)" == "1" ]]; then
    log_pass "a second export rewrites the block in place: no duplication, no churn"
else
    log_fail "idempotent block" "begin markers=$(grep -c 'craftsman:doctrine:begin' AGENTS.md) witness=$(grep -c 'WITNESS' AGENTS.md)"
fi
# the user's text after the block is kept too, and the block is regenerated
printf '\n## After the doctrine\n\nWITNESS-2: keep me.\n' >> AGENTS.md
sed -i.bak 's/\*\*LAYER001\*\*/**LAYER001-STALE**/' AGENTS.md && rm -f AGENTS.md.bak
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q "WITNESS-2: keep me" AGENTS.md && grep -q '\*\*LAYER001\*\*' AGENTS.md && ! grep -q 'LAYER001-STALE' AGENTS.md; then
    log_pass "text after the block is kept and a hand-edited block is regenerated from the engine"
else
    log_fail "block regeneration" "$(grep -n 'LAYER001\|WITNESS-2' AGENTS.md | tr '\n' '|')"
fi
# the same contract for the Copilot instruction file
mkdir -p .github
printf '# Copilot notes\n\nWITNESS-C: prefer small PRs.\n' > .github/copilot-instructions.md
bash "$CLI" export --target copilot >/dev/null 2>&1
if grep -q "WITNESS-C" .github/copilot-instructions.md && grep -q 'craftsman:doctrine:begin' .github/copilot-instructions.md; then
    log_pass "the Copilot instruction file is treated the same way"
else
    log_fail "copilot preservation" "$(head -3 .github/copilot-instructions.md | tr '\n' '|')"
fi

# Review of 95c431e: an orphan begin marker paired with the end of the block
# the first export appended, and the second export deleted everything between
# them. Malformed markers are refused, never guessed.
printf '# Notes\n\n<!-- craftsman:doctrine:begin version=old -->\nWITNESS-3: orphan begin, keep me.\n' > AGENTS.md
cp AGENTS.md orphan.md
RC=0; bash "$CLI" export --target agents-md >/dev/null 2>/tmp/orphan.err || RC=$?
if [[ "$RC" -ne 0 ]] && diff -q orphan.md AGENTS.md >/dev/null && grep -q "marker" /tmp/orphan.err; then
    log_pass "a begin marker without its end refuses the export and leaves the file untouched"
else
    log_fail "orphan begin" "rc=$RC $(head -3 AGENTS.md | tr '\n' '|') err=$(cat /tmp/orphan.err | head -1)"
fi
printf '<!-- craftsman:doctrine:end -->\n# Notes\n<!-- craftsman:doctrine:begin version=old -->\nWITNESS-4\n<!-- craftsman:doctrine:end -->\n' > AGENTS.md
RC=0; bash "$CLI" export --target agents-md >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 ]] && grep -q "WITNESS-4" AGENTS.md; then
    log_pass "two end markers refuse the export and keep the text"
else
    log_fail "ambiguous markers" "rc=$RC"
fi
# Line endings and mode outside the block are the user's. The mode is read
# GNU-first: BSD `stat -f '%Lp'` is a filesystem query on GNU that exits 0
# with `  File: ...`, so the BSD-first fallback never ran on Linux (CI on
# ubuntu-latest read an empty mode).
_mode() { stat -c '%a' "$1" 2>/dev/null || stat -f '%Lp' "$1"; }
printf '# CRLF notes\r\n\r\nWITNESS-5: keep my CRLF.\r\n' > AGENTS.md
chmod 664 AGENTS.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if grep -q $'WITNESS-5: keep my CRLF.\r$' AGENTS.md && grep -q $'craftsman:doctrine:end -->\r$' AGENTS.md \
    && [[ "$(_mode AGENTS.md)" == "664" ]]; then
    log_pass "a CRLF file keeps its line endings (block included) and its mode after the export"
else
    log_fail "CRLF and mode" "mode=$(_mode AGENTS.md) $(head -c 60 AGENTS.md | od -c | head -2 | tr '\n' ' ')"
fi
rm -f orphan.md
rm -f AGENTS.md user-only.md after-one.md

# --- Codex roles from the shared agents ------------------------------------
echo ""
echo "--- codex-agents export ---"
mkdir -p .codex/agents
printf 'name = "mine"\ndescription = "user role"\ndeveloper_instructions = "keep me"\n' > .codex/agents/mine.toml
RC=0; bash "$CLI" export --target codex-agents >/dev/null 2>&1 || RC=$?
ROLE_COUNT=$(ls .codex/agents/craftsman-*.toml 2>/dev/null | wc -l | tr -d ' ')
AGENT_COUNT=$(ls "$ROOT_DIR"/agents/*.md | wc -l | tr -d ' ')
if [[ "$RC" -eq 0 && "$ROLE_COUNT" == "$AGENT_COUNT" && "$ROLE_COUNT" -gt 0 ]]; then
    log_pass "one craftsman-<name>.toml per agents/*.md ($ROLE_COUNT)"
else
    log_fail "codex-agents count" "rc=$RC roles=$ROLE_COUNT agents=$AGENT_COUNT"
fi
if python3 - <<'PYCHECK'
import glob, re, sys, tomllib
ok = True
for path in glob.glob(".codex/agents/craftsman-*.toml"):
    with open(path, "rb") as handle:
        role = tomllib.load(handle)
    ok &= set(role) == {"name", "description", "developer_instructions"}
    ok &= role["name"] == "craftsman-" + re.sub(r"^craftsman-|\.toml$", "", path.split("/")[-1])
    ok &= len(role["developer_instructions"]) > 200 and "---" not in role["developer_instructions"][:5]
sys.exit(0 if ok else 1)
PYCHECK
then
    log_pass "every role parses as TOML with exactly name, description, developer_instructions (no model, tools or effort transposed) and a frontmatter-free body"
else
    log_fail "codex-agents shape" "a role is missing a field, carries a host field, or kept its frontmatter"
fi
if grep -q 'Validates dependency direction' .codex/agents/craftsman-architect.toml \
    && grep -q '^name = "craftsman-architect"' .codex/agents/craftsman-architect.toml \
    && grep -q 'sha256:' .codex/agents/craftsman-architect.toml; then
    log_pass "the architect role carries the source description, the prefixed name and its provenance"
else
    log_fail "architect role" "$(head -4 .codex/agents/craftsman-architect.toml | tr '\n' '|')"
fi
cp .codex/agents/craftsman-architect.toml role-one.toml
bash "$CLI" export --target codex-agents >/dev/null 2>&1
if diff -q role-one.toml .codex/agents/craftsman-architect.toml >/dev/null && grep -q 'keep me' .codex/agents/mine.toml; then
    log_pass "a second export is byte-identical and leaves the user's own role untouched"
else
    log_fail "codex-agents idempotence" "role changed or user role lost"
fi
# --into writes the roles where the caller says (the observed location is
# ~/.codex/agents/; the test uses a private directory, never the real one)
INTO="$WORK/user-codex/agents"
bash "$CLI" export --target codex-agents --into "$INTO" >/dev/null 2>&1
if [[ "$(ls "$INTO"/craftsman-*.toml 2>/dev/null | wc -l | tr -d ' ')" == "$ROLE_COUNT" ]]; then
    log_pass "--into writes the same roles into the directory named"
else
    log_fail "--into" "$(ls "$INTO" 2>/dev/null | tr '\n' ' ')"
fi
rm -rf .codex role-one.toml "$WORK/user-codex"
# Review of ff99dd5: a body with ''' round-trips exactly, and a pre-created
# symlink in .codex/agents is refused, never written through.
mkdir -p .codex/agents agents-probe
printf -- "---\nname: probe\ndescription: probe with \"\"\" and '''\n---\nBody with '''three''' apostrophes, a back\\\\slash and \"\"\"quotes\"\"\".\n" > agents-probe/probe.md
python3 "$ROOT_DIR/ci/agent_roles.py" codex agents-probe .codex/agents >/dev/null 2>&1
if python3 - <<'PYCHECK'
import tomllib, sys
role = tomllib.load(open(".codex/agents/craftsman-probe.toml", "rb"))
body = role["developer_instructions"]
sys.exit(0 if "'''three'''" in body and 'back\\slash' in body and '"""quotes"""' in body and '"""' in role["description"] else 1)
PYCHECK
then
    log_pass "a body holding ''', a backslash and triple quotes decodes byte for byte"
else
    log_fail "TOML round trip" "$(grep -c "''" .codex/agents/craftsman-probe.toml) apostrophe lines; $(python3 -c 'import tomllib;print(repr(tomllib.load(open(".codex/agents/craftsman-probe.toml","rb"))["developer_instructions"][:80]))' 2>&1)"
fi
VICTIM="$WORK/victim.txt"; printf 'keep\n' > "$VICTIM"
rm -f .codex/agents/craftsman-probe.toml
ln -s "$VICTIM" .codex/agents/craftsman-probe.toml
RC=0; python3 "$ROOT_DIR/ci/agent_roles.py" codex agents-probe .codex/agents >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 && "$(cat "$VICTIM")" == "keep" && -L .codex/agents/craftsman-probe.toml ]]; then
    log_pass "a symlinked role file is refused and its target is untouched"
else
    log_fail "symlinked role target" "rc=$RC victim=$(cat "$VICTIM")"
fi
rm -rf .codex/agents; ln -s "$WORK/elsewhere" .codex/agents; mkdir -p "$WORK/elsewhere"
RC=0; python3 "$ROOT_DIR/ci/agent_roles.py" codex agents-probe .codex/agents >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 && -z "$(ls "$WORK/elsewhere")" ]]; then
    log_pass "a symlinked .codex/agents directory is refused, nothing written through it"
else
    log_fail "symlinked roles dir" "rc=$RC wrote: $(ls "$WORK/elsewhere" | tr '\n' ' ')"
fi
rm -rf .codex agents-probe "$WORK/elsewhere"
# Independent verification (2026-09-15): a symlinked parent or target under a
# validated directory carried the write out of the project. Refused now.
# outside means outside the project (the test runs inside $WORK): a sibling directory
OUTSIDE_DIR=$(mktemp -d "${TMPDIR:-/tmp}/craftsman-outside-target.XXXXXX"); mkdir -p .codex
ln -s "$OUTSIDE_DIR" .codex/agents
RC=0; bash "$CLI" export --target codex-agents >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 && -z "$(ls "$OUTSIDE_DIR")" ]]; then
    log_pass "a symlinked .codex/agents parent is refused; nothing lands outside the project"
else
    log_fail "symlinked roles parent" "rc=$RC wrote: $(ls "$OUTSIDE_DIR" | tr '\n' ' ')"
fi
rm -rf .codex "$OUTSIDE_DIR"
rm -rf .github; OUTSIDE_GH=$(mktemp -d "${TMPDIR:-/tmp}/craftsman-outside-gh.XXXXXX"); ln -s "$OUTSIDE_GH" .github
RC=0; bash "$CLI" export --target copilot >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 && ! -e "$OUTSIDE_GH/copilot-instructions.md" ]]; then
    log_pass "a symlinked .github parent is refused for the Copilot instructions"
else
    log_fail "symlinked .github" "rc=$RC $(ls "$OUTSIDE_GH" | tr '\n' ' ')"
fi
rm -f .github; rm -rf "$OUTSIDE_GH"
OUTSIDE_MD=$(mktemp "${TMPDIR:-/tmp}/craftsman-outside-agents.XXXXXX"); printf 'keep\n' > "$OUTSIDE_MD"; ln -s "$OUTSIDE_MD" AGENTS.md
RC=0; bash "$CLI" export --target agents-md >/dev/null 2>&1 || RC=$?
if [[ "$RC" -ne 0 && "$(cat "$OUTSIDE_MD")" == "keep" ]]; then
    log_pass "a symlinked AGENTS.md is refused and its target untouched"
else
    log_fail "symlinked AGENTS.md" "rc=$RC $(cat "$OUTSIDE_MD")"
fi
rm -f AGENTS.md "$OUTSIDE_MD"
# mixed line endings stay mixed outside the block
printf 'USER-CRLF\r\nUSER-LF\n' > AGENTS.md
bash "$CLI" export --target agents-md >/dev/null 2>&1
if head -c 20 AGENTS.md | od -c | grep -q 'C   R   L   F  \\r  \\n' && grep -q $'^USER-LF$' AGENTS.md; then
    log_pass "a file with mixed line endings keeps each line's own ending outside the block"
else
    log_fail "mixed line endings" "$(head -c 24 AGENTS.md | od -c | head -2 | tr '\n' ' ')"
fi
rm -f AGENTS.md

cd "$PREV_PWD"
rm -rf "$WORK"


# A host that discovers hooks/hooks.json and runs none of it still runs a
# project hooks file, and that file is generated from the manifest: typed a
# second time, a wiring drifts from what it mirrors. Grok 1.0.30 is that
# host (measured twice, 2026-09-15 and 2026-09-20).
HH=$(mktemp -d "${TMPDIR:-/tmp}/craftsman-hosthooks.XXXXXX")
HH_OUT=$(cd "$HH" && bash "$CLI" export --target grok-hooks 2>&1)
HH_FILE="$HH/.grok/hooks/craftsman.json"
HH_EVENTS=$(jq -r '.hooks | keys | join(",")' "$HH_FILE" 2>/dev/null)
HH_CMD=$(jq -r '.hooks.PreToolUse[0].hooks[0].command' "$HH_FILE" 2>/dev/null)
HH_MATCH=$(jq -r '.hooks.PreToolUse[0].matcher' "$HH_FILE" 2>/dev/null)
HH_IF=$(jq -r '[.hooks[][] | .hooks[] | select(.command | test("git push"))] | length' "$HH_FILE" 2>/dev/null)
HH_PUSH=$(jq -r '[.hooks[][] | .hooks[] | select(.command | test("pre-push-verify\\.sh"))] | length' "$HH_FILE" 2>/dev/null)
if [[ "$HH_EVENTS" != *TaskCompleted* && "$HH_EVENTS" != *FileChanged* && "$HH_EVENTS" == *PreToolUse* \
    && "$HH_CMD" != *'${CLAUDE_PLUGIN_ROOT}'* && "$HH_CMD" == *"CLAUDE_PLUGIN_ROOT=$ROOT_DIR"* \
    && "$HH_CMD" == *"GROK_PLUGIN_ROOT=$ROOT_DIR"* && "$HH_CMD" != *" PLUGIN_ROOT="* \
    && "$HH_MATCH" == *write* && "$HH_MATCH" == *search_replace* \
    && "$HH_IF" == "0" && "$HH_PUSH" == "1" && "$HH_OUT" == *"--trust"* \
    && "$(jq -r '.hooks.SessionStart[0].hooks[0].timeout' "$HH_FILE")" == "15" \
    && "$(jq -r '.hooks.PreToolUse[0].hooks[0].timeout' "$HH_FILE")" == "15" \
    && "$(jq -r '.craftsman.commit' "$HH_FILE")" == "$(git -C "$ROOT_DIR" rev-parse --short=12 HEAD)" \
    && "$(jq -r '.craftsman.version' "$HH_FILE")" == "$(jq -r '.version' "$ROOT_DIR/.claude-plugin/plugin.json")" \
    && "$(jq -r '.craftsman.root' "$HH_FILE")" == "$(cd "$ROOT_DIR" && pwd -P)" ]]; then
    log_pass "grok-hooks writes the manifest's handlers with the root expanded and carried, drops the events Grok does not fire, keeps pre-push-verify.sh, names write/search_replace, and names the trust step"
else
    log_fail "grok-hooks export" "events=$HH_EVENTS if=$HH_IF match=$HH_MATCH cmd=$(printf '%s' "$HH_CMD" | cut -c1-120)"
fi
CX_OUT=$(cd "$HH" && bash "$CLI" export --target codex-hooks 2>&1)
CX_FILE="$HH/.codex/hooks/craftsman.json"
CX_CMD=$(jq -r '.hooks.PreToolUse[0].hooks[0].command' "$CX_FILE" 2>/dev/null)
if [[ "$CX_CMD" == *"PLUGIN_ROOT=$ROOT_DIR"* && "$CX_CMD" == *" PLUGIN_DATA="* \
    && "$CX_CMD" == *"CLAUDE_PLUGIN_ROOT=$ROOT_DIR"* \
    && "$CX_CMD" != *"GROK_PLUGIN_ROOT="* && "$CX_CMD" != *"GROK_PLUGIN_DATA="* \
    && "$(jq -r '.hooks.PreToolUse[0].hooks[0].timeout' "$CX_FILE")" == "15" \
    && "$(jq -r '.craftsman.root' "$CX_FILE")" == "$(cd "$ROOT_DIR" && pwd -P)" \
    && "$CX_OUT" != *"GROK_PLUGIN"* ]]; then
    log_pass "codex-hooks carries PLUGIN_* and timeout 15, and does not carry GROK_*"
else
    log_fail "codex-hooks export" "$(printf '%s' "$CX_CMD" | cut -c1-160)"
fi
rm -rf "$HH"

GROK_MKT="$ROOT_DIR/.grok-plugin/marketplace.json"
CLAUDE_MKT="$ROOT_DIR/.claude-plugin/marketplace.json"
if [[ "$(jq -r '.plugins[0].name,.plugins[0].version' "$GROK_MKT")" == "$(jq -r '.plugins[0].name,.plugins[0].version' "$CLAUDE_MKT")" \
    && "$(jq -r '.plugins[0].source.type' "$GROK_MKT")" == "local" ]]; then
    log_pass "Grok native marketplace names the same craftsman plugin and version as the Claude index"
else
    log_fail "Grok marketplace" "$(jq -c '.plugins[0]|{name,version,source}' "$GROK_MKT")"
fi
if command -v grok >/dev/null 2>&1; then
    if grok plugin validate "$ROOT_DIR" >/dev/null 2>&1; then
        log_pass "grok plugin validate accepts this tree as a native plugin"
    else
        log_fail "grok plugin validate" "$(grok plugin validate "$ROOT_DIR" 2>&1 | tr '\n' ' ' | cut -c1-160)"
    fi
fi

test_summary
