#!/usr/bin/env python3
"""Project conventions generator (ADR-0022): observe git history and layout,
emit a project-conventions skill.

Usage:
  conventions.py analyze <repo_root>            print inferred conventions
  conventions.py generate <repo_root> <out_dir> write <out_dir>/project-conventions/SKILL.md
  conventions.py signals <repo_root>            print situational signals as JSON
"""
import json
import re
import subprocess
import sys
from collections import Counter
from datetime import datetime, timezone
from pathlib import Path

CONVENTIONAL_RE = re.compile(r"^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([^)]+\))?!?:")
LOG_LIMIT = 200
TEST_DIRS = ["tests", "test", "spec", "__tests__"]
CI_MARKERS = [".github/workflows", ".gitlab-ci.yml", "Jenkinsfile", "bitbucket-pipelines.yml"]
EXISTING_PROJECT_COMMITS = 20

SKILL_TEMPLATE = """---
description: Conventions observed in this repository (commit style, layout, test location). Generated by /craftsman:setup; regenerate with /craftsman:setup --refresh.
user-invocable: false
---

# Project Conventions (observed)

> Generated on {today} from {commit_count} commits and the repository layout. Edit freely: this file is yours. Regenerate with `/craftsman:setup --refresh`.

## Commit style

{commit_style}

## Layout

{layout}

## Test location

{tests}
"""


def _git_subjects(root: Path) -> list[str]:
    try:
        out = subprocess.run(
            ["git", "-C", str(root), "log", f"-{LOG_LIMIT}", "--pretty=%s"],
            capture_output=True, text=True, timeout=15, check=True,
        ).stdout
        return [line for line in out.splitlines() if line.strip()]
    except Exception:
        return []


def _commit_style(subjects: list[str]) -> str:
    if not subjects:
        return "- No git history available."
    conventional = [subject for subject in subjects if CONVENTIONAL_RE.match(subject)]
    ratio = len(conventional) / len(subjects)
    prefixes = Counter(CONVENTIONAL_RE.match(subject).group(1) for subject in conventional)
    top = ", ".join(f"`{prefix}` ({count}x)" for prefix, count in prefixes.most_common(6))
    if ratio >= 0.6:
        return (f"- Conventional Commits ({ratio:.0%} of the last {len(subjects)} commits).\n"
                f"- Prefixes in use: {top}.\n- Follow `type(scope): description`, imperative mood.")
    return (f"- Free-form subjects ({ratio:.0%} conventional). Match the existing tone; "
            "keep subjects under 72 chars, imperative mood.")


def _layout(root: Path) -> str:
    known = ["src", "app", "lib", "hooks", "skills", "agents", "packs", "config",
             "public", "templates", "docs", "scripts", "ci"]
    present = [name for name in known if (root / name).is_dir()]
    lines = [f"- Top-level: {', '.join(f'`{name}/`' for name in present) or 'flat layout'}."]
    for layer in ["Domain", "Application", "Infrastructure", "Presentation"]:
        if list(root.glob(f"src/{layer}")):
            lines.append("- Clean Architecture layers under `src/` (Domain/Application/Infrastructure/Presentation).")
            break
    return "\n".join(lines)


def _tests(root: Path) -> str:
    for name in TEST_DIRS:
        tests_dir = root / name
        if tests_dir.is_dir():
            count = sum(1 for entry in tests_dir.rglob("*") if entry.is_file())
            return f"- Separate `{name}/` tree ({count} files). Put new tests there, mirroring source paths."
    if list(root.glob("src/**/*.test.*")):
        return "- Co-located `*.test.*` files next to sources."
    return "- No test tree detected yet: create `tests/` mirroring source paths."


def _has_tests(root: Path) -> bool:
    if any((root / name).is_dir() for name in TEST_DIRS):
        return True
    return bool(list(root.glob("src/**/*.test.*")))


def _has_ci(root: Path) -> bool:
    return any((root / marker).exists() for marker in CI_MARKERS)


def _signals(root: Path) -> dict:
    commit_count = len(_git_subjects(root))
    has_tests = _has_tests(root)
    has_ci = _has_ci(root)
    existing_project = commit_count >= EXISTING_PROJECT_COMMITS
    return {
        "existing_project": existing_project,
        "commit_count": commit_count,
        "has_tests": has_tests,
        "has_ci": has_ci,
        "legacy_signal": existing_project and (not has_tests or not has_ci),
    }


def render(root: Path) -> str:
    subjects = _git_subjects(root)
    return SKILL_TEMPLATE.format(
        today=datetime.now(timezone.utc).strftime("%Y-%m-%d"),
        commit_count=len(subjects),
        commit_style=_commit_style(subjects),
        layout=_layout(root),
        tests=_tests(root),
    )


def main() -> None:
    if len(sys.argv) < 3:
        print(__doc__, file=sys.stderr)
        sys.exit(1)
    command, root = sys.argv[1], Path(sys.argv[2]).resolve()
    if command == "signals":
        print(json.dumps(_signals(root)))
        return
    content = render(root)
    if command == "analyze":
        print(content)
        return
    if command == "generate" and len(sys.argv) == 4:
        out = Path(sys.argv[3]) / "project-conventions"
        out.mkdir(parents=True, exist_ok=True)
        (out / "SKILL.md").write_text(content)
        print(f"generated: {out / 'SKILL.md'}")
        return
    print(__doc__, file=sys.stderr)
    sys.exit(1)


if __name__ == "__main__":
    main()
