#!/usr/bin/env bash
# =============================================================================
# Export the curated coding skills to the Hermes (agentskills.io) shape.
#
# Six skills, not twenty-two (issue #19): team/parallel/loop/metrics/workflow
# are Claude Code orchestration and would be noise for a Hermes agent. Each
# export strips the Claude-only frontmatter, bundles every referenced
# knowledge/ file under references/ and rewrites the links, so nothing in the
# output points outside its own directory.
#
# Deterministic and idempotent: run it after editing a source skill, commit
# the result. tests/adapters/test-hermes-plugin.sh fails on any dead link.
# =============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
OUT_DIR="$ROOT_DIR/adapters/hermes/skills"
CURATED="refactor legacy debug test spec design"

for name in $CURATED; do
    SRC="$ROOT_DIR/skills/$name/SKILL.md" DEST="$OUT_DIR/craftsman-$name" ROOT="$ROOT_DIR" NAME="$name" \
    python3 - <<'PYEOF'
import os, re, shutil
from pathlib import Path

src = Path(os.environ["SRC"])
dest = Path(os.environ["DEST"])
root = Path(os.environ["ROOT"])
name = os.environ["NAME"]

text = src.read_text()
match = re.match(r"^---\n(.*?)\n---\n(.*)$", text, re.S)
front, body = match.group(1), match.group(2)
description = re.search(r"^description:\s*(.+)$", front, re.M).group(1).strip()

refs = sorted(set(re.findall(r"knowledge/[A-Za-z0-9_/.-]+\.md", body)))
dir_refs = sorted(set(re.findall(r"knowledge/[A-Za-z0-9_/-]+/(?=\s|`|$)", body)))
if dest.exists():
    shutil.rmtree(dest)
(dest / "references").mkdir(parents=True) if (refs or dir_refs) else dest.mkdir(parents=True)
for ref in refs:
    source = root / ref
    if not source.is_file():
        raise SystemExit(f"{name}: referenced file missing in repo: {ref}")
    flat = ref.replace("knowledge/", "").replace("/", "-")
    shutil.copy(source, dest / "references" / flat)
    body = body.replace(ref, f"references/{flat}")
for ref in dir_refs:
    source = root / ref
    if not source.is_dir():
        raise SystemExit(f"{name}: referenced directory missing in repo: {ref}")
    prefix = ref.replace("knowledge/", "").strip("/").replace("/", "-")
    for child in sorted(source.glob("*.md")):
        shutil.copy(child, dest / "references" / f"{prefix}-{child.name}")
    body = body.replace(ref, f"references/ ({prefix}-*) ")

body = re.sub(r"/craftsman:([a-z-]+)", r"the craftsman-\1 skill", body)
body = body.replace("${CLAUDE_PLUGIN_ROOT}", "~/.hermes/plugins/craftsman")

header = (
    "---\n"
    f"name: craftsman-{name}\n"
    f"description: {description}\n"
    "version: 1.0.0\n"
    "platforms: [macos, linux]\n"
    "metadata:\n"
    "  hermes:\n"
    f"    tags: [craftsmanship, {name}]\n"
    "    category: devops\n"
    "    requires_toolsets: [terminal]\n"
    "---\n\n"
    "<!-- Generated by scripts/export-hermes-skills.sh from "
    f"skills/{name}/SKILL.md. Edit the source, then re-run the export. -->\n\n"
    "## When to Use\n\n"
    f"{description}\n\n"
)
(dest / "SKILL.md").write_text(header + body)
print(f"exported craftsman-{name} ({len(refs)} reference(s))")
PYEOF
done

if grep -rn "knowledge/" "$OUT_DIR" --include="SKILL.md" >/dev/null 2>&1; then
    echo "export-hermes-skills: dead knowledge/ link left in output" >&2
    exit 1
fi
echo "export complete: $OUT_DIR"
