#!/usr/bin/env python3
"""Project the plugin's agents as Codex role files.

Usage: agent_roles.py codex <agents dir> <output dir> [--version V]

An agent is one Markdown file with YAML frontmatter and a body (agents/*.md).
The mission text is shared; what differs per host is the envelope. Codex reads
roles as TOML with `name`, `description` and `developer_instructions`
(documented at learn.chatgpt.com/docs/agent-configuration/subagents; the shape
below is the one Codex's own import wrote for a Claude Code agent), from
~/.codex/agents/ (observed loaded by `codex exec`) or a project's
.codex/agents/ (documented). Claude Code's `model`, `effort`, `tools`,
`maxTurns`, `memory` and `isolation` are not transposed: a model alias is a
boundary name, and a tool list means something only to the host that named
the tools. The parent's default subagent model applies.

Each role file is `craftsman-<name>.toml`, owned by this generator (a
provenance line names the source and its sha256), regenerated whole, and
never touching another file in the directory.
"""

from __future__ import annotations

import hashlib
import os
import re
import sys

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def _frontmatter(text: str) -> tuple:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    fields: dict = {}
    key = None
    for line in match.group(1).split("\n"):
        if line.startswith((" ", "\t")):
            if key is not None:
                fields[key] = (fields[key] + "\n" + line.strip()).strip()
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        fields[key] = "" if value in ("|", ">", "|-", ">-") else value.strip("'\"")
    return fields, text[match.end():]


def _literal(text: str) -> str:
    """A TOML multi-line literal string: no escapes, so `'''` inside is the one thing to avoid."""
    return "'''\n" + text.replace("'''", "''\\'").rstrip("\n") + "\n'''"


def _basic(text: str) -> str:
    """A TOML multi-line basic string for the description (escapes honoured)."""
    return '"""\n' + text.replace("\\", "\\\\").replace('"""', '""\\"') + '"""'


def render(source_path: str, version: str) -> tuple:
    with open(source_path, encoding="utf-8") as handle:
        text = handle.read()
    fields, body = _frontmatter(text)
    name = fields.get("name") or os.path.splitext(os.path.basename(source_path))[0]
    if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
        raise ValueError(f"{source_path}: agent name {name!r} is not a role name")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
    description = fields.get("description") or f"Craftsman {name} agent."
    role = "\n".join([
        f"# generated by craftsman-ci export --target codex-agents (craftsman {version}) from agents/{os.path.basename(source_path)} sha256:{digest}",
        "# Regenerate with the export; edit the source agent instead of this file.",
        f'name = "craftsman-{name}"',
        f"description = {_basic(description)}",
        f"developer_instructions = {_literal(body.strip())}",
        "",
    ])
    return f"craftsman-{name}.toml", role


def main(argv: list) -> int:
    if len(argv) < 4 or argv[1] != "codex":
        sys.stderr.write(__doc__)
        return 2
    agents_dir, out_dir = argv[2], argv[3]
    version = argv[5] if len(argv) > 5 and argv[4] == "--version" else "unknown"
    os.makedirs(out_dir, exist_ok=True)
    written = 0
    for entry in sorted(os.listdir(agents_dir)):
        if not entry.endswith(".md"):
            continue
        file_name, role = render(os.path.join(agents_dir, entry), version)
        target = os.path.join(out_dir, file_name)
        with open(target + ".tmp", "w", encoding="utf-8") as handle:
            handle.write(role)
        os.replace(target + ".tmp", target)
        written += 1
    print(f"wrote {written} Codex role file(s) to {out_dir} (craftsman-*.toml; spawn them by name, e.g. craftsman-architect)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
