#!/usr/bin/env python3
"""Project the plugin's agents as Codex role files.

Usage: agent_roles.py codex <agents dir> <output dir> [--version V] [--root DIR] [--extra DIR ...]

`--root` is the installed plugin's absolute path: the agents' bootstrap lines
read `bash "${CLAUDE_PLUGIN_ROOT}/hooks/lib/dispatch-context.sh"`, a variable
Claude Code sets and a Codex role's shell does not have, so the exported role
exited 127 on its first command (challenge review of e2acf22, F7); the path is
substituted at export. `--extra` names further agent directories, the loaded
packs' `agents/`: a fresh clone has no pack symlinks under agents/ and exported
six roles instead of twelve (F8).

An agent is one Markdown file with YAML frontmatter and a body (agents/*.md).
The mission text is shared; what differs per host is the envelope. Codex reads
roles as TOML with `name`, `description` and `developer_instructions`
(documented at learn.chatgpt.com/docs/agent-configuration/subagents; the shape
below is the one Codex's own import wrote for a Claude Code agent), from
~/.codex/agents/ (observed loaded by `codex exec`) or a project's
.codex/agents/ (documented). Claude Code's `model`, `effort`, `tools`,
`maxTurns`, `memory` and `isolation` are not transposed: a model alias is a
boundary name, and a tool list means something only to the host that named
the tools. The parent's default subagent model applies.

Each role file is `craftsman-<name>.toml`, owned by this generator (a
provenance line names the source and its sha256), regenerated whole, and
never touching another file in the directory.
"""

from __future__ import annotations

import hashlib
import os
import re
import sys
import tempfile

FRONTMATTER_RE = re.compile(r"\A---\n(.*?)\n---\n", re.S)


def _frontmatter(text: str) -> tuple:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}, text
    fields: dict = {}
    key = None
    for line in match.group(1).split("\n"):
        if line.startswith((" ", "\t")):
            if key is not None:
                fields[key] = (fields[key] + "\n" + line.strip()).strip()
            continue
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        key, value = key.strip(), value.strip()
        fields[key] = "" if value in ("|", ">", "|-", ">-") else value.strip("'\"")
    return fields, text[match.end():]


ROOT_VARIABLES = ("${CLAUDE_PLUGIN_ROOT}", "$CLAUDE_PLUGIN_ROOT")


def _resolve_root(body: str, root: str) -> str:
    """The installed plugin's path where the body says the host's variable."""
    if not root:
        return body
    for variable in ROOT_VARIABLES:
        body = body.replace(variable, root)
    return body


def _basic(text: str) -> str:
    """A TOML multi-line basic string. Basic, not literal, for both fields: a
    literal string cannot hold `\'\'\'`, and the escape the first cut inserted
    for it stayed in the decoded text (review of ff99dd5, F2). Basic strings
    round-trip any body through their escapes."""
    return '"""\n' + text.replace("\\", "\\\\").replace('"""', '""\\"') + '"""'


def render(source_path: str, version: str, root: str = "") -> tuple:
    with open(source_path, encoding="utf-8") as handle:
        text = handle.read()
    fields, body = _frontmatter(text)
    body = _resolve_root(body, root)
    name = fields.get("name") or os.path.splitext(os.path.basename(source_path))[0]
    if not re.fullmatch(r"[A-Za-z0-9_-]+", name):
        raise ValueError(f"{source_path}: agent name {name!r} is not a role name")
    digest = hashlib.sha256(text.encode("utf-8")).hexdigest()[:16]
    description = fields.get("description") or f"Craftsman {name} agent."
    role = "\n".join([
        f"# generated by craftsman-ci export --target codex-agents (craftsman {version}) from agents/{os.path.basename(source_path)} sha256:{digest}",
        "# Regenerate with the export; edit the source agent instead of this file.",
        f'name = "craftsman-{name}"',
        f"description = {_basic(description)}",
        f"developer_instructions = {_basic(body.strip())}",
        "",
    ])
    return f"craftsman-{name}.toml", role


def _write_role(agents_dir: str, out_dir: str, entry: str, version: str, root: str = "") -> None:
    file_name, role = render(os.path.join(agents_dir, entry), version, root)
    target = os.path.join(out_dir, file_name)
    if os.path.islink(target):
        raise OSError(f"{target} is a symlink; refusing to write through it")
    handle_fd, tmp = tempfile.mkstemp(dir=out_dir, prefix=file_name + ".")
    with os.fdopen(handle_fd, "w", encoding="utf-8") as handle:
        handle.write(role)
    os.replace(tmp, target)


def _output_dir_ok(out_dir: str) -> str:
    """"" when the roles may be written there, else the reason not to.

    The directory itself must be real, and its REAL path must stay under the
    project or under $HOME: a symlinked parent (.codex -> elsewhere) passed the
    first check and the roles landed outside the project (independent
    verification, 2026-09-15).
    """
    if os.path.islink(out_dir) or not os.path.isdir(out_dir):
        return f"{out_dir} is not a real directory; refusing to write roles through it"
    real = os.path.realpath(out_dir)
    roots = (os.path.realpath(os.getcwd()), os.path.realpath(os.path.expanduser("~")))
    if not any(real == root or real.startswith(root + os.sep) for root in roots):
        return f"{out_dir} resolves to {real}, outside the project and $HOME; refusing"
    return ""


def _options(argv: list) -> dict:
    options = {"version": "unknown", "root": "", "extra": []}
    index = 4
    while index < len(argv):
        flag, value = argv[index], argv[index + 1] if index + 1 < len(argv) else ""
        if flag == "--version":
            options["version"] = value
        elif flag == "--root":
            options["root"] = os.path.realpath(value) if value else ""
        elif flag == "--extra":
            options["extra"].append(value)
        index += 2
    return options


def _sources(agents_dir: str, extra: list) -> list:
    """(directory, file) for every agent, core first, one per name."""
    seen, sources = set(), []
    for directory in [agents_dir] + [candidate for candidate in extra if os.path.isdir(candidate)]:
        for entry in sorted(os.listdir(directory)):
            if entry.endswith(".md") and entry not in seen and os.path.isfile(os.path.join(directory, entry)):
                seen.add(entry)
                sources.append((directory, entry))
    return sources


def main(argv: list) -> int:
    if len(argv) < 4 or argv[1] != "codex":
        sys.stderr.write(__doc__)
        return 2
    agents_dir, out_dir = argv[2], argv[3]
    options = _options(argv)
    os.makedirs(out_dir, exist_ok=True)
    refusal = _output_dir_ok(out_dir)
    if refusal:
        sys.stderr.write(f"error: {refusal}\n")
        return 1
    sources = _sources(agents_dir, options["extra"])
    try:
        for directory, entry in sources:
            _write_role(directory, out_dir, entry, options["version"], options["root"])
    except OSError as error:
        sys.stderr.write(f"error: {error}\n")
        return 1
    print(f"wrote {len(sources)} Codex role file(s) to {out_dir} (craftsman-*.toml; spawn them by name, e.g. craftsman-architect)")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
